### ISSUE TITLE
Official Support For C# Client

### ISSUE THREAD

**Issue by Lamby123** [camunda-community-hub/zeebe-client-csharp#120]
We have recently adopted Zeebe within our organisation and would like for you to make the C# Client Officially supported by Camunda/Zeebe rather than being solely a community driven project. 

We are a large enterprise with the majority of systems currently written in C#. 

I will raise an official support request on your JIRA and link this GitHub request.

**Comment by meyerdan** [comment]
https://github.com/camunda-cloud/issues/issues/10

**Comment by Zelldon** [comment]
Nothing I can decide, this is up to @meyerdan and @felix-mueller
