### ISSUE TITLE
Cannot connect to a different Camunda Cluster after connecting once

### ISSUE THREAD

**Issue by jwulf** [camunda-community-hub/zeebe-client-csharp#146]
**Describe the bug**
Running an application against a Camunda Cloud cluster, if you change clusters the application will fail to connect.

**To Reproduce**
1. Run your app against a Camunda Cloud cluster.
2. Reconfigure it to run against a different one.
3. Application throws a 401 error when trying to connect.
4. Delete `~/.zeebe/cloud.token`, and you can connect.

**Expected behavior**
Should be able to connect to any cluster with no issues.

**Comment by Zelldon** [comment]
Next week I'm on vacation but maybe I find some time. I will try to prioritize this and probably tackle that together with https://github.com/zeebe-io/zeebe-client-csharp/issues/114
