### ISSUE TITLE
Response Variables property is not very convenient

### ISSUE THREAD

**Issue by xlegalles** [camunda-community-hub/zeebe-client-csharp#214]
The response `Variables `property is a string and this is not very convenient: the proof is the addition of a `getVariablesAsMap ` method in the java client.

The solution would be to add the same kind of facilities in the C# client: `GetVariablesAsMap `and `GetVariablesAsType `(names are the same as the java ones) that return respectively an `IReadOnlyDictionary<string, object>` and `T`.

Remaining questions are:

- the choice of a JSON serializer i.e. Newtonsoft Json.NET vs MS System.Text.Json as we would add a new dependency to the client. For testing you use the 1st one.
- and this dependency would be exposed because in the `IReadOnlyDictionary<string, object>`, the value could be a `JObject`. 

I can make a PR if you agree.

Thank you

**Comment by Zelldon** [comment]
I will close this, since after discussion we also closed the related PR :) https://github.com/camunda-community-hub/zeebe-client-csharp/pull/220 feel free to reopen it if you disagree.
