### ISSUE TITLE
Zeebe 1.0.0-alpha7 Compatibility

### ISSUE THREAD

**Issue by nazzour** [camunda-community-hub/zeebe-client-csharp#274]
**Is your feature request related to a problem? Please describe.**
Hello, I tried to use the client with a fresh Zeebe 1.0.0-alpha7 installation but obviously did not work because  "This release has a breaking change in the gRPC API - the Deploy Process command request format" (Copied it from @jwulf )

**Describe the solution you'd like**
New version compatible with the new Zeebe 1.0.0-alpha7 release

**Describe alternatives you've considered**
NA

**Additional context**
Please are you planning to release a new version ? Thank you

**Comment by Zelldon** [comment]
Please see https://github.com/camunda-community-hub/zeebe-client-csharp/issues/273

> This or at latest next week. Already working on it.

**Comment by nazzour** [comment]
Thank you @Zelldon
