### ISSUE TITLE
Migrate to .net core 3.1

### ISSUE THREAD

**Issue by Zelldon** [camunda-community-hub/zeebe-client-csharp#277]
Migrating to .net core 3.1 gives us some new possibilities like:

 * Using new interfaces (e.g. IAsyncDisposable, solves https://github.com/camunda-community-hub/zeebe-client-csharp/issues/39)
 * Using new grpc lib (dotnet-grpc) https://grpc.io/blog/grpc-on-dotnetcore/ , which would solve https://github.com/camunda-community-hub/zeebe-client-csharp/issues/194 and gives us better performance https://github.com/LesnyRumcajs/grpc_bench/wiki/2021-04-13-bench-results
 * tbd

Furthermore .net core 2.1 is as LTS only supported until August 21, 2021, see https://dotnet.microsoft.com/platform/support/policy/dotnet-core

**Comment by Christian-Oleson** [comment]
@Zelldon 
.NET Core 3.1 is only supported through December 3, 2022. Are you interested in moving from .NET 2.1 to .NET 5?

**Comment by Christian-Oleson** [comment]
However, regardless, I'll gladly take this one.

**Comment by Christian-Oleson** [comment]
The other question I have is regarding the _client_ project. This one is in .NET Standard. Is there a reason we are targeting standard (E.g. backward compatibility)? If so, I'll leave it alone, if not, I'll address the issue.

**Comment by Zelldon** [comment]
Hey @Christian-Oleson 

thanks for stepping in, to answer your question:

> .NET Core 3.1 is only supported through December 3, 2022. Are you interested in moving from .NET 2.1 to .NET 5? I realize that .NET 5 also is EOL in 2022, but .NET 6 would be very easy to update to, and that would have a very long support life.

I would prefer to go with the LTS versions, we can update this then next year again. 

> The other question I have is regarding the client project. This one is in .NET Standard. Is there a reason we are targeting standard (E.g. backward compatibility)? If so, I'll leave it alone, if not, I'll address the issue.

Yes since it should be used in other libs, no matter of windows, linux etc. As far as I know it would be the best to use .net standard here to have a broader audience and support more versions, but as mentioned .net core 2.1 is already out of life, so I would say we can update to .net standard 2.1 (which is then implemented by .net core 3.x afaik). What do you think? Correct me please if I'm wrong I'm not a .net native :sweat_smile:

**Comment by Christian-Oleson** [comment]
> Hey @Christian-Oleson
> 
> thanks for stepping in, to answer your question:
> 
> > .NET Core 3.1 is only supported through December 3, 2022. Are you interested in moving from .NET 2.1 to .NET 5? I realize that .NET 5 also is EOL in 2022, but .NET 6 would be very easy to update to, and that would have a very long support life.
> 
> I would prefer to go with the LTS versions, we can update this then next year again.

I totally understand. .NET 6 comes out in November, and this should be a LTS version. If you want, I can take on that change if you want (confirm this by) opening the .NET 6 migration issue. 

> 
> > The other question I have is regarding the client project. This one is in .NET Standard. Is there a reason we are targeting standard (E.g. backward compatibility)? If so, I'll leave it alone, if not, I'll address the issue.
> 
> Yes since it should be used in other libs, no matter of windows, Linux, etc. As far as I know, it would be best to use .NET standard here to have a broader audience and support more versions, but as mentioned .net core 2.1 is already out of life, so I would say we can update to .NET standard 2.1 (which is then implemented by .net core 3.x afaik). What do you think? Correct me please if I'm wrong I'm not a .net native 😅

.NET Core and .NET 5 are cross-platform, including Windows, Linux, Mac, etc. If that is the concern, updating this to .NET Core isn't an issue. I wouldn't do this yet, because in .NET Core 3.1 it is still technically valid to reference .NET standard. However, in .NET 5, that replaces standard.

The only time you _DONT_ want to change this is when you end up needed the library to reference .NET Framework. And then, depending on what version of .NET Framework you are referencing, you won't want to update to .NET Standard 2.1. Please let me know if you're desiring to use .NET Framework. 😄

**Comment by Zelldon** [comment]
With https://github.com/camunda-community-hub/zeebe-client-csharp/pull/543 we migrated to .net 7.0
