### ISSUE TITLE
Analyze Repo in Sonartype Lift

### ISSUE THREAD

**Issue by Zelldon** [camunda-community-hub/zeebe-client-csharp#299]
@celanthe

**Comment by celanthe** [comment]
Thanks so much for opening this issue @Zelldon! I've got the analysis running on `main` and also ran one on `release-1.0.0` I will let you know ASAP once I have those results for you!

**Comment by Zelldon** [comment]
Awesome thanks @celanthe

**Comment by celanthe** [comment]
@Zelldon I sent you a message on Slack, I've got those results available for you! :)
