### ISSUE TITLE
I can use the client to start an instance with publishMessageCommand and receive a response containing the process instance key

### ISSUE THREAD

**Issue by Dumbnorix** [camunda-community-hub/zeebe-client-csharp#315]
**Is your feature request related to a problem? Please describe.**
I'm not getting a response when I use  publishMessageCommand to start a process instance

**Describe the solution you'd like**
I need the publish message command to return a response which includes the process instance key

**Describe alternatives you've considered**
N/A

**Additional context**
I'm unsure how this is implemented but assuming this uses the underlying api there is a field **resultEnabled** which by default is set to false, meaning publishMessageCommand has no response.

**Comment by Zelldon** [comment]
Hey @Dumbnorix 

thanks for raising this. Unfortunately this is not something we can implement easily on the client side.

Messages are correlated asynchronously and independent. It can happen that the message is published on partition X and the instance where it is correlated to is on partition Y.

You could use an exporter to find out to which instance it was correlated. But maybe it helps alao to raise this on the main project. https://github.com/camunda-cloud/zeebe
