### ISSUE TITLE
Upgrade our issue templates to use GitHub issue forms

### ISSUE THREAD

**Issue by Hard-Coder05** [camunda-community-hub/zeebe-client-csharp#326]
__Is your feature request related to a problem? Please describe.__

GitHub has recently rolled out a [public beta for their issue forms](https://github.blog/changelog/2021-06-23-issues-forms-beta-for-public-repositories/) feature. This would allow you to create interactive issue templates and validate them 🤯.

__Describe the solution you'd like__

This repository currently uses the older issue template format. Your task is to create GitHub issue forms for this repository. We can use this repo's issue templates as a reference for this PR.

**Comment by Hard-Coder05** [comment]
I would like to work on this issue!

**Comment by Christian-Oleson** [comment]
I didn't realize my comment on this one didn't go through when I originally was looking at it... so I opened a PR against the repo but didn't explicitly say I would do it. Sorry folks...

**Comment by Hard-Coder05** [comment]
> I didn't realize my comment on this one didn't go through when I originally was looking at it... so I opened a PR against the repo but didn't explicitly say I would do it. Sorry folks...

@Christian-Oleson I guess this is not acceptable. Until and unless an issue is assigned to someone how can you make a PR? 

@Zelldon do look into this! I hope justice shall be done 😃 !

**Comment by Christian-Oleson** [comment]
> > I didn't realize my comment on this one didn't go through when I originally was looking at it... so I opened a PR against the repo but didn't explicitly say I would do it. Sorry folks...
> 
> @Christian-Oleson I guess this is not acceptable. Until and unless an issue is assigned to someone how can you make a PR?
> 
> @Zelldon do look into this! I hope justice shall be done 😃 !

I will just close my PR then. No worries.

**Comment by Zelldon** [comment]
Hey @Hard-Coder05 thanks for opening this and making me aware, but I would rather like not to do it right now. This is something I would take a closer look myself, but feel free to check one of the other open issues we have here https://github.com/camunda-community-hub/zeebe-client-csharp/issues

**Comment by Hard-Coder05** [comment]
@Zelldon Sure! I will look into other issues then! I am  closing this issue then!
