### ISSUE TITLE
User task job handler not activated

### ISSUE THREAD

**Issue by Ar4ics** [camunda-community-hub/zeebe-client-csharp#367]
I have following code to complete user tasks:
```
public static async Task Main(string[] args)
{
    var zeebeClient = GetClient();
    RegisterUserTasksHandler(zeebeClient);
    Console.ReadKey();
}

private static void RegisterUserTasksHandler(IZeebeClient client)
{
    var jobType = "io.camunda.zeebe:userTask";
    
    var worker = client.NewWorker()
        .JobType(jobType)
        .Handler(JobHandler)
        .Name($"{Environment.MachineName}_{jobType}")
        .PollInterval(TimeSpan.FromSeconds(5))
        .Timeout(TimeSpan.FromSeconds(10))
        .PollingTimeout(TimeSpan.FromSeconds(10))
        .Open();
}

private static async Task JobHandler(IJobClient client, IJob activatedJob)
{
    await client.NewCompleteJobCommand(activatedJob)
        .Send();
}
```
When user task has started, the method JobHandler not launched.
What I'm doing wrong?

**Comment by Zelldon** [comment]
Hey @Ar4ics 

thanks for reporting. Could you please share an example process model so I can reproduce it? Do you see any errors in the log? Broker or client?

How do you run Zeebe? Are you using Camunda cloud?

Greets
Chris

**Comment by Ar4ics** [comment]
Hi @Zelldon. 
I am using example bpmn from [send-email](https://github.com/camunda-cloud/camunda-cloud-get-started/blob/master/process/send-email.bpmn)
Zeebe 1.2.4 was deployed in Camunda Cloud Self-Managed.

Its interesting that if I add line `MaxJobsActive(1)` then JobHandler gets called:
```
client.NewWorker()
    .JobType(jobType)
    .Handler(JobHandler)
    .MaxJobsActive(1)
    .Name($"{Environment.MachineName}_{jobType}")
    .PollInterval(TimeSpan.FromSeconds(5))
    .Timeout(TimeSpan.FromSeconds(10))
    .PollingTimeout(TimeSpan.FromSeconds(10))
    .Open();
```

But without this line its not called.

**Comment by Zelldon** [comment]
Hey @Ar4ics 

Thanks for the additional comment. This makes totally sense. Currently the maxJobsActive if not set, default to zero, which would cause to not active any jobs.

I can increase the default to one.
