### ISSUE TITLE
DefaultWaitTimeProvider has a min wait time of 30s

### ISSUE THREAD

**Issue by csleead** [camunda-community-hub/zeebe-client-csharp#380]
https://github.com/camunda-community-hub/zeebe-client-csharp/blob/bfc0fbca7b177e9fd3816e8da37bdbce108cebf5/Client/ZeebeClient.cs#L37-L38

The `Math.Max` should be `Math.Min`.

**Comment by Zelldon** [comment]
Great catch @csleead thanks for reporting I will create a new release with the fix
