### ISSUE TITLE
Update Doxygen documentation

### ISSUE THREAD

**Issue by falko** [camunda-community-hub/zeebe-client-csharp#383]
The API docs at https://camunda-community-hub.github.io/zeebe-client-csharp/index.html show version `1.0.0` and  `Generated on Tue May 11 2021 15:19:16`. Could they be updated to reflect the latest state?

**Comment by Zelldon** [comment]
@falko https://camunda-community-hub.github.io/zeebe-client-csharp/ should work now let me know if you see any issues
