### ISSUE TITLE
Simplify in the Zeebe C# client the builder.UseTransportEncryption

### ISSUE THREAD

**Issue by arjangeertsema** [camunda-community-hub/zeebe-client-csharp#385]
Simplify in the Zeebe C# client the builder.UseTransportEncryption so it accepts null and defaults to the default encryption.

Related to pull request: https://github.com/camunda-community-hub/zeebe-client-csharp-bootstrap/pull/27

**Comment by Zelldon** [comment]
I don't think that we need this right now
