### ISSUE TITLE
Gateway addresses prefixed with https:// or http:// lead to DNS Resultion Exceptions

### ISSUE THREAD

**Issue by jonathanlukas** [camunda-community-hub/zeebe-client-csharp#502]
**Describe the bug**
Using a gateway address prefixed with http:// or https:// will lead to DNS Resolution Exceptions.

**To Reproduce**
1. Use the Zeebe Client Builder
2. As gateway address, use a value prefixed with https:// or http://
3. run the program
4. DNS resolution failed

**Expected behavior**
The client is able to remove the protocol prefix (maybe pop a warning about it) or throw a more explicit exception.

Alternatively, document it clearly so that a user can find out what went wrong really quick.

**Enviroment (please complete the following information):**
 - OS: MacOS Ventura 13.2.1
 - .NET 7
 - Version 1.3

**Comment by MernaMustafa** [comment]
I have the same issue while using Camunda Platform 8 Self-Managed, is there any workaround to get over it?

**Comment by jonathanlukas** [comment]
Just leave out the prefix.

Instead configure the usage of tls in the other build steps
