### ISSUE TITLE
I can use the client to deploy decision table dmn and get decisionsMetadata

### ISSUE THREAD

**Issue by KevMyst** [camunda-community-hub/zeebe-client-csharp#507]
**Is your feature request related to a problem? Please describe.**
When i used the client to deploy dmn response not contains decisionsMetadata.

**Describe the solution you'd like**
Use the client to deploy dmn and get decisionsMetadata from response.

**Describe alternatives you've considered**
Example of using a client to retrieve decisionsMetadata for the deploy action.

**Comment by Zelldon** [comment]
@KevMyst please take a look at the last releases we have now support for this
