### ISSUE TITLE
Compatibility with .NET framework 4.5

### ISSUE THREAD

**Issue by vincentgiraud** [camunda-community-hub/zeebe-client-csharp#514]
**Is your feature request related to a problem? Please describe.**
To orchestrate a legacy system on .NET framework 4.5 (.NET standard 1.1) using Camunda 8 Enterprise.
The Zeebe csharp client only support .NET framework 4.6.1 and above (.NET standard 2.0)

**Describe the solution you'd like**
Backward compatibility with .NET framework 4.5

**Describe alternatives you've considered**
Upgrading the legacy system won't be an option due to time and cost constraint.

**Comment by Zelldon** [comment]
We migrated to .net 7.0, we will likely not support .net standard 1.1, I will close this issue as won't fix.

Please consider creating a separate project or fork this, and adjust it to your needs. I'm not able to support this due to time constraints and work on other projects.
