### ISSUE TITLE
Migration to grpc-dotnet is not actually done

### ISSUE THREAD

**Issue by jSharpWolf** [camunda-community-hub/zeebe-client-csharp#554]
**Describe the bug**
The migration issue has been closed with release 2.0 (https://github.com/camunda-community-hub/zeebe-client-csharp/issues/348), however the migration is incomplete, and Grpc.Core is still being used. Thus using the ZbClient fails on M1 macs.

In this commit https://github.com/camunda-community-hub/zeebe-client-csharp/pull/545/commits/ee36df81601090b621d08bb99d37ec03cc8480e7 a new package was added, but the code hasn't been adjusted to use the new package. Instead, the "Grpc" dependency  has not been changed (2.46.6) and still uses Grpc.Core

**To Reproduce**
Check in IDE - it clearly still refers to Grpc.Core:
![image](https://github.com/camunda-community-hub/zeebe-client-csharp/assets/17483149/9218469e-c909-4a44-b15e-56280b204349)

or

Try to connect to a Zeebe broker on M1 macs 

**Expected behavior**
The client should not depend on Grpc.Core. The Grpc Nuget package should not be listed in the Client.csproj. 

The classes also differ, this is how it should be:
![image](https://github.com/camunda-community-hub/zeebe-client-csharp/assets/17483149/5a0bf98f-0f99-4d1f-afcd-229d14bf6145)

Instead of using "Channel" "GrpcChannel" must be used, instead of using "ChannelOptions" GrpcChannelOptions" must be used

**Comment by Zelldon** [comment]
Interesting! Thanks for the report, I must have overseen this somehow sorry. I try to take a look as soon as I can.

**Comment by Zelldon** [comment]
@jSharpWolf thanks for reporting! It should be fixed with the latest release https://github.com/camunda-community-hub/zeebe-client-csharp/releases/tag/2.1.0 

I migrated to the new Grpc.net.GrpcChannel and had to migrate several other things, but it should be done now. Be aware Grpc.Core will not completely go away, since it contains several utilities which are also used in Grpc.net.
