### ISSUE TITLE
Add .variables() in .newThrowErrorCommand() command

### ISSUE THREAD

**Issue by pierre-yves-monnet** [camunda-community-hub/zeebe-client-csharp#568]
**Is your feature request related to a problem? Please describe.**
When the worker throws an error, it would like to add an error code and a message. In the JAVA CLient library, the concept is to use the  .variables() method.

`
jobClient.newThrowErrorCommand(job)
.errorCode("creditCardChargeError")
.variables(Map.of("errorCode", "No more credit"))
.errorMessage(e.getMessage()).send().join();
`

**Describe the solution you'd like**
Add the .variables() method, as it exists in the JAVA Client

**Describe alternatives you've considered**
No alternatives is available at this moment

**Additional context**
See https://jira.camunda.com/browse/SUPPORT-17753

**Comment by camundaryan** [comment]
This could be a huge add for us!
