### ISSUE TITLE
.NET LTS support

### ISSUE THREAD

**Issue by daghsentinel** [camunda-community-hub/zeebe-client-csharp#571]
**Is your feature request related to a problem? Please describe.**
.NET 6.0 is an LTS version which has end of support _later_ than .NET 7.0. Some of us tend to use frameworks that do not need yearly updates.

**Describe the solution you'd like**
The client should support LTS version, including .NET 6

**Describe alternatives you've considered**
Upgrading 120+ repositories to .NET 7 only due to the zeebe-client being the only library solely supporting .NET 7 is not an option

**Comment by xlegalles** [comment]
@Zelldon because I did it originally in my PR, I know what to do and it should be quick. Do you want me to do a PR?

**Comment by Zelldon** [comment]
I'm wondering what the proposed solution would be. A new release with downgraded .net version?

**Comment by xlegalles** [comment]
No, I would do a multi target build. As a result a single nuget package
would contain both versions.

**Comment by Zelldon** [comment]
Ah I see. Yeah if you like you can create a PR and we take a look together.

**Comment by Zelldon** [comment]
Thanks @daghsentinel for reporting again and @xlegalles for the contribution 🎉 Release 2.2.0 is out :) https://github.com/camunda-community-hub/zeebe-client-csharp/releases/tag/2.2.0 -> nuget https://www.nuget.org/packages/zb-client/2.2.0

**Comment by daghsentinel** [comment]
Great work! Love it!
